// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Suporte Técnico",
            "email": "suporte@exemplo.com.br"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actions": {
            "get": {
                "description": "Retorna lista de ações com diversos filtros dinâmicos (Eixo, Programa, Ano, etc).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actions"
                ],
                "summary": "Listar Ações (Matriz/Planos)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Bacia",
                        "name": "basin_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ano de vigência (ex: 2024)",
                        "name": "ano",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtro por nome do Eixo",
                        "name": "eixo",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtro por nome do Programa",
                        "name": "programa",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtro por Tipologia",
                        "name": "tipologia",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Busca textual na descrição",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/actions/filters": {
            "get": {
                "description": "Retorna listas únicas de Eixos, Programas e Tipologias para preencher combos do frontend.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actions"
                ],
                "summary": "Opções de Filtro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Bacia",
                        "name": "basin_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/content": {
            "get": {
                "description": "Retorna os textos hierárquicos (1.1, 1.2...) para montar a página de leitura",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content"
                ],
                "summary": "Textos do Plano",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Bacia",
                        "name": "basin_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Section"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/consolidated": {
            "get": {
                "description": "Retorna IEA Máximo, IEA Atual e Índice Global",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dados Consolidados (Cards)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Bacia (Padrão: 1)",
                        "name": "basin_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ConsolidatedStats"
                        }
                    }
                }
            }
        },
        "/dashboard/radar": {
            "get": {
                "description": "Retorna soma dos pesos agrupados por tipologia (Obra, Estudo, etc)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dados do Gráfico Radar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Bacia (Padrão: 1)",
                        "name": "basin_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number",
                                "format": "float64"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ConsolidatedStats": {
            "type": "object",
            "properties": {
                "basin_id": {
                    "description": "\u003c--- NOVO: Vincula à bacia (Salgado)",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "iea_max": {
                    "type": "number"
                },
                "iea_min": {
                    "type": "number"
                },
                "indice_atual": {
                    "type": "number"
                },
                "indice_global": {
                    "type": "number"
                },
                "reference_month": {
                    "type": "string"
                },
                "total_actions": {
                    "type": "integer"
                }
            }
        },
        "model.Section": {
            "type": "object",
            "properties": {
                "basin_id": {
                    "description": "Referência opcional à bacia (caso expanda para outras bacias no futuro)",
                    "type": "integer"
                },
                "content": {
                    "description": "O texto longo",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "description": "1, 2, 3... (Nível hierárquico para o frontend indentar)",
                    "type": "integer"
                },
                "number": {
                    "description": "Ex: \"1\", \"1.1\", \"3.4.1\"",
                    "type": "string"
                },
                "title": {
                    "description": "Ex: \"Infraestrutura Hídrica\"",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Regiões Hidrográficas API",
	Description:      "API para monitoramento, gestão e visualização dos Planos de Recursos Hídricos (Curu, Salgado, etc).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
